In [1]:
from twone import RNNContainer
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(np.reshape(np.arange(30000), (3, -1)).T, columns=['a', 'b', 'c'])

In [3]:
feature_tags = ['a', 'b']
target_tags = ['c']

In [4]:
container = RNNContainer(df)

In [5]:
container.set_feature_tags(feature_tags)
container.set_target_tags(target_tags)

In [6]:
container.data

a      b      c  c_target
0        0  10000  20000   20001.0
1        1  10001  20001   20002.0
2        2  10002  20002   20003.0
3        3  10003  20003   20004.0
4        4  10004  20004   20005.0
5        5  10005  20005   20006.0
6        6  10006  20006   20007.0
7        7  10007  20007   20008.0
8        8  10008  20008   20009.0
9        9  10009  20009   20010.0
10      10  10010  20010   20011.0
11      11  10011  20011   20012.0
12      12  10012  20012   20013.0
13      13  10013  20013   20014.0
14      14  10014  20014   20015.0
15      15  10015  20015   20016.0
16      16  10016  20016   20017.0
17      17  10017  20017   20018.0
18      18  10018  20018   20019.0
19      19  10019  20019   20020.0
20      20  10020  20020   20021.0
21      21  10021  20021   20022.0
22      22  10022  20022   20023.0
23      23  10023  20023   20024.0
24      24  10024  20024   20025.0
25      25  10025  20025   20026.0
26      26  10026  20026   20027.0
27      27  10027  20027   20028.0
28      28  10028  20028   20029.0
29      29  10029  20029   20030.0
...    ...    ...    ...       ...
9969  9969  19969  29969   29970.0
9970  9970  19970  29970   29971.0
9971  9971  19971  29971   29972.0
9972  9972  19972  29972   29973.0
9973  9973  19973  29973   29974.0
9974  9974  19974  29974   29975.0
9975  9975  19975  29975   29976.0
9976  9976  19976  29976   29977.0
9977  9977  19977  29977   29978.0
9978  9978  19978  29978   29979.0
9979  9979  19979  29979   29980.0
9980  9980  19980  29980   29981.0
9981  9981  19981  29981   29982.0
9982  9982  19982  29982   29983.0
9983  9983  19983  29983   29984.0
9984  9984  19984  29984   29985.0
9985  9985  19985  29985   29986.0
9986  9986  19986  29986   29987.0
9987  9987  19987  29987   29988.0
9988  9988  19988  29988   29989.0
9989  9989  19989  29989   29990.0
9990  9990  19990  29990   29991.0
9991  9991  19991  29991   29992.0
9992  9992  19992  29992   29993.0
9993  9993  19993  29993   29994.0
9994  9994  19994  29994   29995.0
9995  9995  19995  29995   29996.0
9996  9996  19996  29996   29997.0
9997  9997  19997  29997   29998.0
9998  9998  19998  29998   29999.0

[9999 rows x 4 columns]

In [7]:
container.gen_batch(batch=5, time_steps=100)

sequences_length:  1300
time_steps:  100
sequences_length:  400
time_steps:  100
sequences_length:  200
time_steps:  100


D:\anaconda\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [8]:
container.get_training_features()

array([[[  599., 10599., 20599.],
        [  600., 10600., 20600.],
        [  601., 10601., 20601.],
        ...,
        [  696., 10696., 20696.],
        [  697., 10697., 20697.],
        [  698., 10698., 20698.]],

       [[ 2499., 12499., 22499.],
        [ 2500., 12500., 22500.],
        [ 2501., 12501., 22501.],
        ...,
        [ 2596., 12596., 22596.],
        [ 2597., 12597., 22597.],
        [ 2598., 12598., 22598.]],

       [[ 4399., 14399., 24399.],
        [ 4400., 14400., 24400.],
        [ 4401., 14401., 24401.],
        ...,
        [ 4496., 14496., 24496.],
        [ 4497., 14497., 24497.],
        [ 4498., 14498., 24498.]],

       [[ 6299., 16299., 26299.],
        [ 6300., 16300., 26300.],
        [ 6301., 16301., 26301.],
        ...,
        [ 6396., 16396., 26396.],
        [ 6397., 16397., 26397.],
        [ 6398., 16398., 26398.]],

       [[ 8199., 18199., 28199.],
        [ 8200., 18200., 28200.],
        [ 8201., 18201., 28201.],
        ...,
        [

In [9]:
container.get_training_targets()

array([[[20600.],
        [20601.],
        [20602.],
        [20603.],
        [20604.],
        [20605.],
        [20606.],
        [20607.],
        [20608.],
        [20609.],
        [20610.],
        [20611.],
        [20612.],
        [20613.],
        [20614.],
        [20615.],
        [20616.],
        [20617.],
        [20618.],
        [20619.],
        [20620.],
        [20621.],
        [20622.],
        [20623.],
        [20624.],
        [20625.],
        [20626.],
        [20627.],
        [20628.],
        [20629.],
        [20630.],
        [20631.],
        [20632.],
        [20633.],
        [20634.],
        [20635.],
        [20636.],
        [20637.],
        [20638.],
        [20639.],
        [20640.],
        [20641.],
        [20642.],
        [20643.],
        [20644.],
        [20645.],
        [20646.],
        [20647.],
        [20648.],
        [20649.],
        [20650.],
        [20651.],
        [20652.],
        [20653.],
        [20654.],
        [2

In [10]:
container.get_cv_features()

array([[[ 1899., 11899., 21899.],
        [ 1900., 11900., 21900.],
        [ 1901., 11901., 21901.],
        ...,
        [ 1996., 11996., 21996.],
        [ 1997., 11997., 21997.],
        [ 1998., 11998., 21998.]],

       [[ 3799., 13799., 23799.],
        [ 3800., 13800., 23800.],
        [ 3801., 13801., 23801.],
        ...,
        [ 3896., 13896., 23896.],
        [ 3897., 13897., 23897.],
        [ 3898., 13898., 23898.]],

       [[ 5699., 15699., 25699.],
        [ 5700., 15700., 25700.],
        [ 5701., 15701., 25701.],
        ...,
        [ 5796., 15796., 25796.],
        [ 5797., 15797., 25797.],
        [ 5798., 15798., 25798.]],

       [[ 7599., 17599., 27599.],
        [ 7600., 17600., 27600.],
        [ 7601., 17601., 27601.],
        ...,
        [ 7696., 17696., 27696.],
        [ 7697., 17697., 27697.],
        [ 7698., 17698., 27698.]],

       [[ 9499., 19499., 29499.],
        [ 9500., 19500., 29500.],
        [ 9501., 19501., 29501.],
        ...,
        [

In [11]:
container.get_cv_targets()

array([[[21900.],
        [21901.],
        [21902.],
        [21903.],
        [21904.],
        [21905.],
        [21906.],
        [21907.],
        [21908.],
        [21909.],
        [21910.],
        [21911.],
        [21912.],
        [21913.],
        [21914.],
        [21915.],
        [21916.],
        [21917.],
        [21918.],
        [21919.],
        [21920.],
        [21921.],
        [21922.],
        [21923.],
        [21924.],
        [21925.],
        [21926.],
        [21927.],
        [21928.],
        [21929.],
        [21930.],
        [21931.],
        [21932.],
        [21933.],
        [21934.],
        [21935.],
        [21936.],
        [21937.],
        [21938.],
        [21939.],
        [21940.],
        [21941.],
        [21942.],
        [21943.],
        [21944.],
        [21945.],
        [21946.],
        [21947.],
        [21948.],
        [21949.],
        [21950.],
        [21951.],
        [21952.],
        [21953.],
        [21954.],
        [2